trigger:
  branches:
    include:
      - main
      - feature/ci

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define common variables
  backendAppName: 'aistudy-backend'
  middlewareAppName: 'aistudy-middleware'
  frontendAppName: 'aistudy-frontend'
  backendDockerImage: 'aistudy1.azurecr.io/aistudy/backend-service:$(Build.BuildId)'
  middlewareDockerImage: 'aistudy1.azurecr.io/aistudy/middleware-service:$(Build.BuildId)'
  frontendDockerImage: 'aistudy1.azurecr.io/aistudy/frontend:$(Build.BuildId)'
  containerRegistry: 'Labs Container'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildBackend
        displayName: 'Build Backend'
        steps:
          # Download and install Microsoft OpenJDK 17.0.12
          - script: |
              echo "Installing Microsoft OpenJDK 17.0.12..."
              wget https://aka.ms/download-jdk/microsoft-jdk-17.0.12-linux-x64.tar.gz -O microsoft-jdk-17.tar.gz
              mkdir -p /usr/lib/jvm/microsoft-jdk-17
              tar -xzf microsoft-jdk-17.tar.gz -C /usr/lib/jvm/microsoft-jdk-17 --strip-components=1
              # Set JAVA_HOME and update the PATH
              export JAVA_HOME=/usr/lib/jvm/microsoft-jdk-17
              export PATH=$JAVA_HOME/bin:$PATH
              # Verify the installation
              java -version
              javac -version
            displayName: 'Install and Verify Microsoft OpenJDK 17.0.12'
            # Verify the JDK and Maven configuration
          - script: |
              echo "Validating JDK installation..."
              echo "JAVA_HOME: $JAVA_HOME"
              java -version
              javac -version
              which java
              which javac
              echo "Maven JAVA_HOME: $(mvn -v | grep 'Java home')"
              echo "Maven Java version: $(mvn -v | grep 'Java version')"
            displayName: 'Verify JDK and Maven Configuration'
          # Build the backend
          - script: |
              cd backend
              ./mvnw clean package
            displayName: 'Build Java Backend'

      - job: BuildMiddleware
        displayName: 'Build Middleware'
        steps:
          # Download and install Microsoft OpenJDK 17.0.12
          - script: |
              echo "Installing Microsoft OpenJDK 17.0.12..."
              wget https://aka.ms/download-jdk/microsoft-jdk-17.0.12-linux-x64.tar.gz -O microsoft-jdk-17.tar.gz
              mkdir -p /usr/lib/jvm/microsoft-jdk-17
              tar -xzf microsoft-jdk-17.tar.gz -C /usr/lib/jvm/microsoft-jdk-17 --strip-components=1
              # Set JAVA_HOME and update the PATH
              export JAVA_HOME=/usr/lib/jvm/microsoft-jdk-17
              export PATH=$JAVA_HOME/bin:$PATH
              # Verify the installation
              java -version
              javac -version
            displayName: 'Install and Verify Microsoft OpenJDK 17.0.12'
          # Verify the JDK and Maven configuration
          - script: |
              echo "Validating JDK installation..."
              echo "JAVA_HOME: $JAVA_HOME"
              java -version
              javac -version
              which java
              which javac
              echo "Maven JAVA_HOME: $(mvn -v | grep 'Java home')"
              echo "Maven Java version: $(mvn -v | grep 'Java version')"
          # Build the backend
          - script: |
              cd middleware
              ./mvnw clean package
            displayName: 'Build Java Middleware'

      - job: BuildFrontend
        displayName: 'Build Frontend'
        steps:
          - script: |
              cd frontend
              npm install
              npm run build
            displayName: 'Build React Frontend'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - deployment: DeployBackend
        displayName: 'Deploy Backend'
        environment: 'backend-env'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Docker@2
                  inputs:
                    command: 'buildAndPush'
                    repository: $(backendDockerImage)
                    Dockerfile: 'backend/Dockerfile'
                    containerRegistry: $(containerRegistry)
                    tags: $(Build.BuildId)
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Labs'
                    appType: 'webAppLinux'
                    appName: 'aistudy-backend'
                    package: '$(System.DefaultWorkingDirectory)/backend/target/*.war'

      - deployment: DeployMiddleware
        displayName: 'Deploy Middleware'
        environment: 'middleware-env'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Docker@2
                  inputs:
                    command: 'buildAndPush'
                    repository: $(middlewareDockerImage)
                    Dockerfile: 'middleware/Dockerfile'
                    containerRegistry: $(containerRegistry)
                    tags: |
                      $(Build.BuildId)
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Labs'
                    appType: 'webAppLinux'
                    appName: 'aistudy-middleware'
                    package: '$(System.DefaultWorkingDirectory)/middleware/target/*.war'

      - deployment: DeployFrontend
        displayName: 'Deploy Frontend'
        environment: 'frontend-env'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Docker@2
                  inputs:
                    command: 'buildAndPush'
                    repository: $(frontendDockerImage)
                    Dockerfile: 'frontend/Dockerfile'
                    containerRegistry: $(containerRegistry)
                    tags: |
                      $(Build.BuildId)
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Labs'
                    appType: 'webAppLinux'
                    appName: 'aistudy-frontend'
                    package: '$(System.DefaultWorkingDirectory)/frontend/build'
                    startUpCommand: 'pm2 serve /home/site/wwwroot/build --no-daemon --spa'
