trigger:
  branches:
    include:
      - main
      - feature/ci

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Maven@4
  inputs:
    azureSubscription: 'Labs'
    mavenPomFile: 'backend/pom.xml'
    mavenVersionOption: 'Default'
    jdkVersionOption: 1.17
    jdkArchitectureOption: x64
    publishJUnitResults: false
    goals: package
