apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: <YOUR_ACR_URL>.azurecr.io/backend-image:v1
          ports:
            - containerPort: 8080
          env:
            - name: AZURE_KEYVAULT_URL
              value: https://<KEY_VAULT_NAME>.vault.azure.net/
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
