apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
        - name: middleware
          image: <ACR_NAME>.azurecr.io/aistudy/middleware:latest
          ports:
            - containerPort: 8080
          env:
            - name: AZURE_KEYVAULT_URI
              value: <AZURE_KEYVAULT_URI>
---
apiVersion: v1
kind: Service
metadata:
  name: middleware-service
spec:
  selector:
    app: middleware
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
