spring:
  application:
    name: backend
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true # Enables loading Key Vault secrets into Spring properties
          property-sources:
            - name: "StorageAccountName"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "StorageContainerName"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "AzureCosmosConnectionString"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "MongoDBDatabaseName"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "MiddlewareServiceBaseUrl"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "MiddlewareServiceAccessKey"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "MiddlewareServiceProductEmbeddingEndpoint"
              endpoint: ${AZURE_KEYVAULT_URI}
      storage:
        account-name: ${StorageAccountName}  # Name of the secret in Key Vault for storage account
        blob:
          container-name: ${StorageContainerName}  # Name of the secret in Key Vault for container name
          account-name: ${StorageAccountName}
  data:
    mongodb:
      uri: ${AzureCosmosConnectionString}
      database: ${MongoDBDatabaseName}

data:
  customer:
    path: src/main/resources/static/customer/data.json
  product:
    path: src/main/resources/static/product/sku.json
  append:
    enabled: true

#logging:      # Enable Debug Log
#  level:
#    org.springframework.cloud.azure: DEBUG
#    com.azure: DEBUG

