spring:
  application:
    name: middleware
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true # Enables loading Key Vault secrets into Spring properties
          property-sources:
            - name: "BackendServiceBaseUrl"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "BackendServiceProductEndpoint"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "BackendServiceSimilarProductEndpoint"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "BackendServiceAccessKey"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "AzureOpenAiEndpointUrl"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "AzureOpenAiAccessKey"
              endpoint: ${AZURE_KEYVAULT_URI}
            - name: "AzureOpenAiEmbeddingEndpointUrl"
              endpoint: ${AZURE_KEYVAULT_URI}

## Application Configuration

## Local Development Settings
## Uncomment the line below to change the port number for local development.
## This will avoid conflicts with other Java services running on the same port.
## For example, set the port to 8081 if the default port 8080 is in use.

#server:
#  port: 8081

#logging:      # Enable Debug Log
#  level:
#    org.springframework.cloud.azure: DEBUG
#    com.azure: DEBUG
